name: Railway Nightly Schedule

on:
  schedule:
    # 8:00 PM COT (01:00 AM UTC) - Apagar Servicio
    - cron: '0 1 * * *'
    # 8:00 AM COT (01:00 PM UTC) - Encender Servicio
    - cron: '0 13 * * *'
  workflow_dispatch: # Permite probar la ejecucion manualmente desde GitHub Actions

jobs:
  manage-service:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar Railway CLI
        run: npm install -g @railway/cli

      - name: Apagar Servicio (8:00 PM COT)
        if: github.event.schedule == '0 1 * * *' || github.event_name == 'workflow_dispatch'
        run: railway down --service=$SERVICE_ID --environment=$ENV_ID -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: "ef6b5897-c616-48ee-be1f-f0d77d9c3e12"
          ENV_ID: "59722f34-6a1f-4904-a008-cd7465552df5"

      - name: Encender Servicio (8:00 AM COT)
        if: github.event.schedule == '0 13 * * *'
        run: railway redeploy --service=$SERVICE_ID --environment=$ENV_ID -y
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SERVICE_ID: "ef6b5897-c616-48ee-be1f-f0d77d9c3e12"
          ENV_ID: "59722f34-6a1f-4904-a008-cd7465552df5"
